
spring:
  datasource:
    url: jdbc:mysql://192.168.1.2:3306/yundi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: guard
    password: cOmmverge13
    driver-class-name: com.mysql.cj.jdbc.Driver
