
spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://192.168.1.2:3306/yundi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: guard
    password: cOmmverge13
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

logging:
  file:
    path: /tmp
  level:
    com.commverge.kafka: debug



person:
  name: calfen
  age: 47
  departperson:
    - xuhongbin
    - maxiujun
    - qiubin
    - ruanjianghang

---

spring:
  config:
    activate:
      on-profile: product
  datasource:
    url: jdbc:mysql://192.168.1.2:3306/yundi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: guard
    password: cOmmverge13
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

logging:
  level: error
  file:
    path: /tmp

